### PR TITLE
Remove poxis dependency, unnecessary with the v6.0 of NodeJS

### PR DESCRIPTION
**Pull request by demsking**
The problem with the posix dependency is that it depend of a C module, and its compilation on some cloud machine without some rights is not possible.
So now cronicle use native NodeJS calls to get user info.
PS. cronicle is very awesome!

### CODE REVIEW

**Comment by jhuckaby** [comment]
Thank you very much for this PR, but I'm afraid there is a problem.  Node 6's new `os.userInfo()` only returns information about the *current* user.  That's not what I need.  You see, Cronicle allows you to enter *any* username on the system, and it resolves that username to its proper UID, along with other information.  This line of code here is very important:

```js
var user_info = posix.getpwnam( child_opts.uid ); 
```

Notice that `child_opts.uid` is passed into the function as an argument.  That is the user we need to "look up" to get its UID, home directory, and such.  Node's `os.userInfo()` does not provide this, as it only resolves the current user (which is always root, and so the UID is always 0 -- not useful to us).

Sorry, but thank you for your efforts!

**Comment by demsking** [comment]
Thanks for your review, I understand.

I wrote this because on my company the installation of the package _posix_ didt not work because restricted rights. My NodeJS is running in the user mode (not root), so `os.userInfo()` resolve the current user (which is never root). So for my usecase and my rights constraints, `os.userInfo()` is the same that `posix.getpwnam( child_opts.uid )`. Cronicle work fine with multi-servers.

PS. I love the logo, its awesome!
:-)

**Comment by jhuckaby** [comment]
Ah, I understand.  I can attempt to make the `posix` package an optional dependency, and only load it if present on the system, and then just disable the "Advanced Features" panel when it is not available.  However, this will take some doing, so I am not sure how soon I can get to this.

Good luck making it work on Windows!  I suspect that will take some serious effort, not only because of filesystem path separators, but also because of how child processes are spawned, how they communicate with each other, and how resources are monitored.

Thanks again for your work on this!

**Comment by jhuckaby** [comment]
FYI, I just released v0.5.7, which has built-in native support for getting user information (custom function, based on [passwd-user](https://github.com/sindresorhus/passwd-user)).  This removes the last remaining C/C++ dependency, so now Cronicle can be installed without compilation.

Commit: https://github.com/jhuckaby/Cronicle/commit/3e3ef678197bfcf22b88249896a9afcf06147f40

Tag: https://github.com/jhuckaby/Cronicle/releases/tag/v0.5.7

Hope this helps!

\- Joe

**Pull request closed without merging**
