### PR TITLE
Fix for newly added remote_server_port

### PR DESCRIPTION
**Pull request by seanford**
Simple fix as the config pull was missing ".server"

Added field to sample config.json as well.

### CODE REVIEW

**Comment by jhuckaby** [comment]
Oops, thank you for catching this, @seanford!  I will fix the bug in the code right this very second, but I really don't want to include `remote_server_port` in the sample config file.  Doing so would mean that new users would have to change their port in 2 places, which I don't like.

**Comment by jhuckaby** [comment]
Fixed in [v0.9.32](https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.32).  Thank you!  Closing this PR now.

**Comment by seanford** [comment]
One last thing....the remote_server_port is working for servers that are already added, but if you try and Add a server, it does not use the port.  I'm guessing this is in admin.js, but I haven't dove into the code yet.

**Comment by jhuckaby** [comment]
Uh oh... this is a can of worms... I actually see several places where this needs to be fixed.  Fetching job logs from a worker server, etc.  But the code uses a utility function that doesn't differentiate between masters and workers.  Ugh...

Working on it...

**Comment by seanford** [comment]
Sorry about that....

Suggestion for Orchestra....use a function to construct the api calls, so that if you ever need to make a change, you only have to do it in one place.  I saw someone do that once, and I've been doing it ever since.

**Comment by jhuckaby** [comment]
Hopefully this does it: https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.33

🤞🏻

**Comment by seanford** [comment]
What about a proxy from the desired port to 3012.  Realistically all I wanted was to be able to use the admin on port 80 on the master.  Can your built in web server do that?   Or listen on more than one port?    Might be easier.   Call it secondary_web_port.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jhuckaby** [comment]
The web server does not have that feature, sorry.

This should be fixed in v0.9.33.

Disclaimer added to doc.

**Pull request closed without merging**
