### PR TITLE
Fixes: Live logs, View Full Log & Download Log in single instance/master behind LB.

### PR DESCRIPTION
**Pull request by BitProcessor**
Uses an extra entry in the client object in config.json:
```
	"client": {
		"custom_live_log_socket_url": "https://example.com",
```

### CODE REVIEW

**Comment by jhuckaby** [comment]
Thanks for this!  But unfortunately, you (probably inadvertently) changed all the spacing in the file, rendering the diff virtually unreadable:

https://github.com/jhuckaby/Cronicle/pull/228/files

I can't see where the actual changes are, because there are so many whitespace changes.  This is probably just something weird going on with your text editor.  Don't worry tho, I'll try to locate the specific non-whitespace changes you made, and just manually apply them to the master branch.

Thanks for your work on this!

**Comment by jhuckaby** [comment]
Change applied in https://github.com/jhuckaby/Cronicle/commit/55c64899d8de6cd55a1ac436ef600860d293dcad

Thanks again!

**Comment by BitProcessor** [comment]
I think it automatically replaces all tabs with a number of spaces. Seems you have found the changes though. If you want to double heck: they all had a comment with ‘BitProcessor’ in them. Thanks for merging! :-D

**Comment by BitProcessor** [comment]
> @BitProcessor it should fix #123, right ?

If it's a single master setup => yes

**Comment by lukasmrtvy** [comment]
@BitProcessor 

it should work as environment variable out of the box, isnt it ?
I am using:

-  `CRONICLE_base_app_url='https://cronicle.example.com' `
- `CRONICLE_custom_live_log_socket_url='https://cronicle.example.com' `

, but I am still getting:
```
Log Watcher: Server Connect Error: Error: websocket error (https://172.18.0.38:3013)
```

**Comment by lukasmrtvy** [comment]
Ups, sorry, its working with `CRONICLE_client__custom_live_log_socket_url`

**Comment by jhuckaby** [comment]
@lukasmrtvy No, the thing is, the new `custom_live_log_socket_url` isn't a top-level configuration property.  It lives inside the `client` object, so you would have to format the environment variable like this:

```
CRONICLE_client__custom_live_log_socket_url='https://cronicle.example.com'
```

Notice there are **two** underscores there (`__`), which denotes a sub-object traversal.  This is explained in the [Environment Variables](https://github.com/jhuckaby/Cronicle#environment-variables) section in the main docs:

> For overriding configuration properties by environment variable, you can specify any top-level JSON key from `config.json`, or a *path* to a nested property using double-underscore (`__`) as a path separator.  For boolean properties, you can specify `1` for true and `0` for false.  

Hope this helps.

**Pull request closed without merging**
